# Generated by Django 4.2.6 on 2023-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('mon', models.CharField(max_length=25)),
                ('tue', models.CharField(max_length=25)),
                ('wed', models.CharField(max_length=25)),
                ('thu', models.CharField(max_length=25)),
                ('fri', models.CharField(max_length=25)),
            ],
        ),
    ]
