# Generated by Django 4.2.6 on 2023-10-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_branch2_branch3_profs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profs',
            new_name='prof',
        ),
    ]
