# Generated by Django 4.2.6 on 2023-10-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_profs_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch1',
            name='fri',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch1',
            name='mon',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch1',
            name='thu',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch1',
            name='tue',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch1',
            name='wed',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch2',
            name='fri',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch2',
            name='mon',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch2',
            name='thu',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch2',
            name='tue',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch2',
            name='wed',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch3',
            name='fri',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch3',
            name='mon',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch3',
            name='thu',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch3',
            name='tue',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='branch3',
            name='wed',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
